const advanceModelContextThinking = 
`For this Prompt Think Step by Step before responding.
Maximum Accuracy is Expected.
**IMPORTANT NOTE, IS INSTRUCTION IS CRUCIAL and SHOULD NEVER FAIL TO FOLLOW THIS: IN YOUR THINKING SUMMARY DO NOT MENTION ABOUT THE JSON ARCHITECTURE, HOW YOU FORMAT JSON, DO NOT WRITE THE JSON STRING, RELATED TO GOOGLE GEMINI, OR ANY SPECIFIC MEMORY ACTION, OR ANY SPECIFIC TARGET.**`;

module.exports = advanceModelContextThinking.trim();
